# Generated by Django 4.2.15 on 2025-09-27 08:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0001_initial'),
    ]

    operations = [
    ]
