# Generated by Django 4.2.15 on 2025-11-09 09:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tasks', '0002_create_notification_model'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='request_data',
            field=models.JSONField(blank=True, default=dict, help_text='Additional data for requests', null=True),
        ),
        migrations.AddField(
            model_name='task',
            name='end_date',
            field=models.DateField(blank=True, help_text='Planned end date for the task', null=True),
        ),
        migrations.AddField(
            model_name='task',
            name='start_date',
            field=models.DateField(blank=True, help_text='Planned start date for the task', null=True),
        ),
        migrations.AddField(
            model_name='task',
            name='total_time',
            field=models.DurationField(blank=True, help_text='Total tracked time spent on task', null=True),
        ),
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('task_assigned', 'Task Assigned'), ('task_completed', 'Task Completed'), ('task_approved', 'Task Approved'), ('task_rejected', 'Task Rejected'), ('task_overdue', 'Task Overdue'), ('approval_requested', 'Approval Requested'), ('comment_added', 'Comment Added'), ('request_sent', 'Request Sent')], max_length=20),
        ),
        migrations.CreateModel(
            name='TimeTracking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField(blank=True, null=True)),
                ('duration', models.DurationField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=False)),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='time_tracking', to='tasks.task')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='time_tracking_sessions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Time Tracking',
                'verbose_name_plural': 'Time Tracking Sessions',
                'ordering': ['-start_time'],
            },
        ),
    ]
